### ISSUE TITLE
autovideoconverter/HandBrakeCLI not applying nice

### ISSUE THREAD

**Issue by spannerman79** [jlesage/docker-handbrake#206]
My docker-compose.yml

```
version: '3'
services:
  handbrake:
    image: jlesage/handbrake:latest
    cap_add:
      - SYS_NICE
    ports:
      - '5800:5800'
      - '5900:5900'
    volumes:
      - '/share/CACHEDEV1_DATA/docker_data/handbrake:/config:rw'
      - '/share/CACHEDEV1_DATA:/storage:ro'
      - '/share/CACHEDEV1_DATA/docker_data/handbrake/watch:/watch:rw'
      - '/share/CACHEDEV1_DATA/docker_data/handbrake/output:/output:rw'
    environment:
      - TZ=Australia/Sydney
      - VNC_PASSWORD=removed
      - USER_ID=0
      - GROUP_ID=0
      - SUP_GROUP_IDS=1000
      - KEEP_APP_RUNNING=1
      - APP_NICENESS=19
      - AUTOMATED_CONVERSION_PRESET=removed
      - AUTOMATED_CONVERSION_SOURCE_STABLE_TIME=10
      - AUTOMATED_CONVERSION_OUTPUT_SUBDIR=SAME_AS_SRC
      - DISPLAY_WIDTH=1920
      - DISPLAY_HEIGHT=1080
      - AUTOMATED_CONVERSION_KEEP_SOURCE=0
```

As you can see by the docker compose, I have both added SYS_NICE & have the required env var defined, but yet when viewing `htop` I see the nice value of the auto conversion is zero as well as HandBrakeCLI which is spawned under and including `bash run s6/services/autovideoconverter/autovideoconverter`, which means it wasn't ran with a nice value defined.

**Comment by spannerman79** [comment]
Further testing shows that nice is only applied if the conversion process is started via WebUI/VNC.

I see that the process `/usr/bin/ghb --config /config` has a nice value of 19 as defined via `APP_NICENESS=19`

So the docker container is setup correctly, just the `AUTOMATED_CONVERSION` process doesn't use the configured env var.

**Comment by jlesage** [comment]
Thanks for reporting, I will fix that.

**Comment by spannerman79** [comment]
Thanks.  When you want feedback please let me know so I can test/report.  If fixed I can close this issue.

**Comment by jlesage** [comment]
I forgot to update this issue, but this should be fixed now.

**Comment by spannerman79** [comment]
Well I just did a quick check, unfortunately no it isn't resolved.

Using most up to date image via dockerhub;

```
docker pull jlesage/handbrake:latest
latest: Pulling from jlesage/handbrake
Digest: sha256:4f433d8dcf43a2ab4cf750430cad504af3f717e1c55b749dbf7c8bd97a090df5
Status: Image is up to date for jlesage/handbrake:latest
docker.io/jlesage/handbrake:latest
```
I actually use https://github.com/containrrr/watchtower to check for and automate updating running containers every 6 hours so I know the image is usually current give or take 6 odd hours.

Nice value is `0` which is unset/normal when checking the PID.
